FROM adoptopenjdk:11-jre-hotspot
ENTRYPOINT ["java","-jar","/out/artifacts/tp1_docker_postgres_jar/tp1_docker_postgres.jar"]
ADD target/*jar-with-dependencies.jar /out/artifacts/tp1_docker_postgres_jar/tp1_docker_postgres.jar